#!/usr/bin/env bash
# scripts/invoke-onchain.sh
# Pushes the proofs generated by e2e-demo.sh to the deployed Soroban contracts
# and walks the full compliance gate live on testnet:
#   1. register the PoR policy + submit the reserves proof  -> on-chain attestation
#   2. register the eligibility gate policy
#   3. call rwa_gate.authorize_receive() with the eligibility proof  -> ✅ opens
#   4. call it AGAIN with the same proof                              -> ❌ nullifier replay
#
# This is the "aha moment" for the demo video. It assumes:
#   - scripts/build-circuits.sh has produced the zkeys/VKs
#   - scripts/deploy.sh has written build/deploy.<net>.json
#   - scripts/e2e-demo.sh has written build/e2e/{reserves_proof,eligibility_proof,allowlist}.json
#   - GROTH16_VERIFIER_ID is set and the *_vk_soroban.json keys are registered with it
#     (see docs/UPGRADE.md "Wiring the groth16_verifier")
#
# Encoding helpers: the Groth16Proof / PublicSignals structs are passed as JSON via
# `--arg-file`. The exact field layout is produced by prover/src/soroban-format.js.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NET="${STELLAR_NETWORK:-testnet}"
SRC="${STELLAR_IDENTITY:-aegis-deployer}"
DEPLOY="$ROOT/build/deploy.${NET}.json"
WORK="$ROOT/build/e2e"

[ -f "$DEPLOY" ] || { echo "Missing $DEPLOY — run scripts/deploy.sh first"; exit 1; }
[ -f "$WORK/reserves_proof.json" ] || { echo "Missing proofs — run scripts/e2e-demo.sh first"; exit 1; }

jqget () { node -e "console.log(require('$DEPLOY').$1)"; }
POR_ID="$(jqget por_verifier)"
ELIG_ID="$(jqget eligibility_verifier)"
GATE_ID="$(jqget rwa_gate)"
ADMIN="$(jqget admin)"

# A demo RWA token address. In a real deployment this is your SAC / asset contract.
TOKEN="${RWA_TOKEN_ID:-$ADMIN}"
GATE_BYTES32="${ELIGIBILITY_GATE_ID:-0000000000000000000000000000000000000000000000000000000000000001}"

# --- helper: turn the prover's soroban JSON into a stellar-cli --arg-file payload ---
proof_args () { # $1 = proof json file ; emits the structured args the contract expects
  node "$ROOT/scripts/encode-invoke-args.mjs" "$1"
}

be32 () { node -e "let v=BigInt(process.argv[1]);console.log(v.toString(16).padStart(64,'0'))" "$1"; }

echo "######## 1. Register PoR policy + attest ########"
COMMIT_DEC="$(node -e "console.log(require('$WORK/reserves_proof.json').reservesCommitment)")"
COMMIT_BE32="$(be32 "$COMMIT_DEC")"
stellar contract invoke --id "$POR_ID" --source "$SRC" --network "$NET" -- \
  set_policy --token "$TOKEN" --issuer "$ADMIN" \
  --reserves_commitment "$COMMIT_BE32" --min_collateral_bps 10000 --vk_id 0

# The proof + signals are large structs; we pass them via a generated arg file.
node "$ROOT/scripts/encode-invoke-args.mjs" "$WORK/reserves_proof.json" attest > "$WORK/attest.args.json"
stellar contract invoke --id "$POR_ID" --source "$SRC" --network "$NET" \
  --arg-file "$WORK/attest.args.json" -- attest || {
    echo "  (if this failed on byte-encoding, flip G2_FP2_ORDER — see docs/UPGRADE.md)"; }

echo "######## 2. Register eligibility gate policy ########"
ISSUER_X="$(be32 "$(node -e "console.log(require('$WORK/credential.json').issuerPubKeyX)")")"
ISSUER_Y="$(be32 "$(node -e "console.log(require('$WORK/credential.json').issuerPubKeyY)")")"
ROOT_BE32="$(be32 "$(node -e "console.log(require('$WORK/allowlist.json').root)")")"
stellar contract invoke --id "$ELIG_ID" --source "$SRC" --network "$NET" -- \
  set_gate --admin "$ADMIN" --gate_id "$GATE_BYTES32" --policy "{\
\"issuer_pubkey_x\":\"$ISSUER_X\",\"issuer_pubkey_y\":\"$ISSUER_Y\",\
\"required_kyc_level\":2,\"require_accredited\":true,\
\"allowed_jurisdiction_root\":\"$ROOT_BE32\",\
\"action_id\":\"0000000000000000000000000000000000000000000000000000000000000309\",\
\"vk_id\":1,\"max_skew_secs\":3600}"

echo "######## 3. Configure the gate + authorize_receive (EXPECT ✅) ########"
stellar contract invoke --id "$GATE_ID" --source "$SRC" --network "$NET" -- \
  configure --admin "$ADMIN" --config "{\
\"token\":\"$TOKEN\",\"por_verifier\":\"$POR_ID\",\
\"eligibility_verifier\":\"$ELIG_ID\",\
\"eligibility_gate_id\":\"$GATE_BYTES32\",\"max_reserve_age_secs\":86400}"

node "$ROOT/scripts/encode-invoke-args.mjs" "$WORK/eligibility_proof.json" authorize_receive \
  --token "$TOKEN" --receiver "$ADMIN" > "$WORK/authorize.args.json"
echo ">>> first call (should AUTHORIZE):"
stellar contract invoke --id "$GATE_ID" --source "$SRC" --network "$NET" \
  --arg-file "$WORK/authorize.args.json" -- authorize_receive

echo "######## 4. Replay the SAME proof (EXPECT ❌ NullifierUsed) ########"
echo ">>> second call (should REJECT):"
if stellar contract invoke --id "$GATE_ID" --source "$SRC" --network "$NET" \
     --arg-file "$WORK/authorize.args.json" -- authorize_receive; then
  echo "  ✗ UNEXPECTED: replay succeeded — investigate nullifier storage"; exit 1
else
  echo "  ✓ EXPECTED: replay rejected (nullifier already spent)"
fi

echo ""
echo "✓ Live gate demo complete on $NET."
echo "  Explorer: https://stellar.expert/explorer/$NET/contract/$GATE_ID"
